
list = ["Milk", "Bread", "butter", "eggs"]
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list)
list.pop(2)
print(list)
list.remove("eggs")
print(list)
list.append("sugar")
print(list)
list.sort()
print(list)
list.reverse()
print(list)
list.insert(2,"flour")
print(list)